export{ default as Root } from "./MainTitle.svelte"
export{ default as BreadcrumbsES } from "./ESBreadcrumb.svelte"
export{ default as BreadcrumbsEN } from "./ENreadcrumb.svelte"
export{ default as BreadcrumbsPT } from "./PTBreadcrumb.svelte"
export{ default as MainLogo } from "./MainLogo.svelte"
